version: '3.8'

volumes:
  postgres-data:

services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-java:stable-1
    init: true
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_PASSWORD: 12qwaszx
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      
  db:
    container_name: higiadb_dev
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: 12qwaszx
      POSTGRES_USER: root
      POSTGRES_DB: higiadb_dev

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)