# APLICATION
server.port: ${PORT:5000}
server.environment: ${ENVIRONMENT:development}

spring.datasource.url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mydb}
hibernate.connection.url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username: ${DB_USERNAME:root}
spring.datasource.password: ${DB_PASSWORD:12qwaszx}
spring.datasource.driver-class-name: ${DB_DRIVE:org.postgresql.Driver}
spring.jpa.database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
# spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

# SWAGGER
springdoc.swagger-ui.path: /docs
springdoc.api-docs.path: /docs-api
springdoc.swagger-ui.tryItOutEnabled: true
springdoc.swagger-ui.filter: true
openapi.dev-url: http://localhost:${PORT:5000}
openapi.prod-url: ${APP_URL}